name: nlp_env
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas>=1.0.0
  - pip
  - pycodestyle=2.5.0
  - python=3.7.*
  - spacy=3.4.*
  - spacy-model-en_core_web_sm=3.4.*
  - pytest=4.4.*
  - pytest-xdist>=1.28.0
  - pytest-sugar=0.9.*
  - pytest-cov
  - scipy
  - numpy
  - scikit-learn
  - pip:
    - nltk>=3.4.3
    - langid>=1.1.6
prefix: /anaconda3/envs/nlp_env
